export const MILLISECONDS_IN_ONE_SECOND = 1000;
export const MILLISECONDS_IN_ONE_MINUTE = MILLISECONDS_IN_ONE_SECOND * 60;
export const MILLISECONDS_IN_ONE_HOUR = MILLISECONDS_IN_ONE_MINUTE * 60;
export const MILLISECONDS_IN_ONE_DAY = MILLISECONDS_IN_ONE_HOUR * 24;
export const MILLISECONDS_IN_ONE_WEEK = MILLISECONDS_IN_ONE_DAY * 7;
export const SECONDS_IN_ONE_MINUTE = 60;
export const SECONDS_IN_ONE_HOUR = SECONDS_IN_ONE_MINUTE * SECONDS_IN_ONE_MINUTE;

export const KNOWN_NON_DURATION_LABELS = new Set([
  'ESTREIA',
  'AO VIVO',
  'EM BREVE',
]);

export const TIME_PATTERN = /^\d+(?::\d+){0,2}$/;
